name: Upload Python Package

on:
  release:
    types: [published]

jobs:
  pypi-publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Set up Python
        uses: astral-sh/setup-uv@v5

      - name: Install dependencies
        run: uv sync --all-extras --dev

      - name: Build package
        run: ds build

      - name: Publish package
        uses: pypa/gh-action-pypi-publish@2f6f737ca5f74c637829c0f5c3acd0e29ea5e8bf
